### ISSUE TITLE
Checkout of Issue ONETEAM-429 failed: Error : Unable to parse component description for nrdk

### ISSUE THREAD

**Issue by 2011sandeepraj** [BCDevOps/nrdk#22]
Steps to reproduce:
`~/TeamZero$` npx @bcgov/nrdk backlog:checkout ONETEAM-429
? 'userPrincipalName' for 'IDIR' (e-mail format- e.g.: john.doe@gov.bc.ca) [REDACTED]
? 'password' for 'IDIR' [hidden]
Fetching Jira Issue ONETEAM-429... done
    Error: Unable to parse component description for nrdk`

Log when run in DEBUG mode

`winston:create-logger: Define prototype method for "error"
winston:create-logger: Define prototype method for "warn"
winston:create-logger: Define prototype method for "info"
winston:create-logger: Define prototype method for "http"
winston:create-logger: Define prototype method for "verbose"
winston:create-logger: Define prototype method for "debug"
winston:create-logger: Define prototype method for "silly"
winston:create-logger: Define prototype method for "error"
winston:create-logger: Define prototype method for "warn"
winston:create-logger: Define prototype method for "info"
winston:create-logger: Define prototype method for "http"
winston:create-logger: Define prototype method for "verbose"
winston:create-logger: Define prototype method for "debug"
winston:create-logger: Define prototype method for "silly"
  @oclif/config reading core plugin /home/satandon/TeamZero/git/fork/nrdk +0ms
  @oclif/config loadJSON /home/satandon/TeamZero/git/fork/nrdk/package.json +0ms
  @oclif/config loadJSON /home/satandon/TeamZero/git/fork/nrdk/oclif.manifest.json +8ms
  @oclif/config:@bcgov/nrdk using manifest from /home/satandon/TeamZero/git/fork/nrdk/oclif.manifest.json +0ms
  @oclif/config reading user plugins pjson /home/satandon/.local/share/@bcgov/nrdk/package.json +0ms
  @oclif/config loadJSON /home/satandon/.local/share/@bcgov/nrdk/package.json +6ms
  @oclif/config loading plugins [ '@oclif/plugin-help' ] +1ms
  @oclif/config reading core plugin /home/satandon/TeamZero/git/fork/nrdk/node_modules/@oclif/plugin-help +0ms
  @oclif/config loadJSON /home/satandon/TeamZero/git/fork/nrdk/node_modules/@oclif/plugin-help/package.json +4ms
  @oclif/config loadJSON /home/satandon/TeamZero/git/fork/nrdk/node_modules/@oclif/plugin-help/oclif.manifest.json +6ms
  @oclif/config:@oclif/plugin-help using manifest from /home/satandon/TeamZero/git/fork/nrdk/node_modules/@oclif/plugin-help/oclif.manifest.json +0ms
  @oclif/config config done +12ms
  @oclif/config start init hook +1ms
  @oclif/config init hook done +1ms
  nrdk init version: @oclif/command@1.8.0 argv: [ 'backlog:checkout', 'ONETEAM-429' ] +0ms
  @oclif/config runCommand backlog:checkout [ 'ONETEAM-429' ] +15ms
  @oclif/config registering ts-node at /home/satandon/TeamZero/git/fork/nrdk +0ms
  @oclif/config:@bcgov/nrdk require /home/satandon/TeamZero/git/fork/nrdk/src/commands/backlog/checkout.ts +439ms
  @oclif/config start prerun hook +1s
  @oclif/config prerun hook done +0ms
winston:create-logger: Define prototype method for "error"
winston:create-logger: Define prototype method for "warn"
winston:create-logger: Define prototype method for "help"
winston:create-logger: Define prototype method for "data"
winston:create-logger: Define prototype method for "info"
winston:create-logger: Define prototype method for "debug"
winston:create-logger: Define prototype method for "prompt"
winston:create-logger: Define prototype method for "verbose"
winston:create-logger: Define prototype method for "input"
winston:create-logger: Define prototype method for "silly"
? 'userPrincipalName' for 'IDIR' (e-mail format- e.g.: john.doe@gov.bc.ca) 
satandon@CA-L9C241G2:~/TeamZero$ npx @bcgov/nrdk backlog:checkout ONETEAM-429
? 'userPrincipalName' for 'IDIR' (e-mail format- e.g.: john.doe@gov.bc.ca) sandeepraj.tandon@gov.bc.ca
? 'password' for 'IDIR' [hidden]
Fetching Jira Issue ONETEAM-429... done
    Error: Unable to parse component description for nrdk
satandon@CA-L9C241G2:~/TeamZero$ DEBUG=* npx @bcgov/nrdk backlog:checkout ONETEAM-429
winston:create-logger: Define prototype method for "error"
winston:create-logger: Define prototype method for "warn"
winston:create-logger: Define prototype method for "info"
winston:create-logger: Define prototype method for "http"
winston:create-logger: Define prototype method for "verbose"
winston:create-logger: Define prototype method for "debug"
winston:create-logger: Define prototype method for "silly"
winston:create-logger: Define prototype method for "error"
winston:create-logger: Define prototype method for "warn"
winston:create-logger: Define prototype method for "info"
winston:create-logger: Define prototype method for "http"
winston:create-logger: Define prototype method for "verbose"
winston:create-logger: Define prototype method for "debug"
winston:create-logger: Define prototype method for "silly"
  @oclif/config reading core plugin /home/satandon/TeamZero/git/fork/nrdk +0ms
  @oclif/config loadJSON /home/satandon/TeamZero/git/fork/nrdk/package.json +0ms
  @oclif/config loadJSON /home/satandon/TeamZero/git/fork/nrdk/oclif.manifest.json +8ms
  @oclif/config:@bcgov/nrdk using manifest from /home/satandon/TeamZero/git/fork/nrdk/oclif.manifest.json +0ms
  @oclif/config reading user plugins pjson /home/satandon/.local/share/@bcgov/nrdk/package.json +0ms
  @oclif/config loadJSON /home/satandon/.local/share/@bcgov/nrdk/package.json +4ms
  @oclif/config loading plugins [ '@oclif/plugin-help' ] +1ms
  @oclif/config reading core plugin /home/satandon/TeamZero/git/fork/nrdk/node_modules/@oclif/plugin-help +0ms
  @oclif/config loadJSON /home/satandon/TeamZero/git/fork/nrdk/node_modules/@oclif/plugin-help/package.json +4ms
  @oclif/config loadJSON /home/satandon/TeamZero/git/fork/nrdk/node_modules/@oclif/plugin-help/oclif.manifest.json +5ms
  @oclif/config:@oclif/plugin-help using manifest from /home/satandon/TeamZero/git/fork/nrdk/node_modules/@oclif/plugin-help/oclif.manifest.json +0ms
  @oclif/config config done +13ms
  @oclif/config start init hook +1ms
  @oclif/config init hook done +1ms
  nrdk init version: @oclif/command@1.8.0 argv: [ 'backlog:checkout', 'ONETEAM-429' ] +0ms
  @oclif/config runCommand backlog:checkout [ 'ONETEAM-429' ] +11ms
  @oclif/config registering ts-node at /home/satandon/TeamZero/git/fork/nrdk +0ms
  @oclif/config:@bcgov/nrdk require /home/satandon/TeamZero/git/fork/nrdk/src/commands/backlog/checkout.ts +370ms
  @oclif/config start prerun hook +1s
  @oclif/config prerun hook done +0ms
winston:create-logger: Define prototype method for "error"
winston:create-logger: Define prototype method for "warn"
winston:create-logger: Define prototype method for "help"
winston:create-logger: Define prototype method for "data"
winston:create-logger: Define prototype method for "info"
winston:create-logger: Define prototype method for "debug"
winston:create-logger: Define prototype method for "prompt"
winston:create-logger: Define prototype method for "verbose"
winston:create-logger: Define prototype method for "input"
winston:create-logger: Define prototype method for "silly"
? 'userPrincipalName' for 'IDIR' (e-mail format- e.g.: john.doe@gov.bc.ca) sandeepraj.tandon@gov.bc.ca
? 'password' for 'IDIR' [hidden]
  follow-redirects options {
  maxRedirects: 21,
  maxBodyLength: 10485760,
  protocol: 'https:',
  path: '/int/jira/rest/api/2/issue/ONETEAM-429?fields=issuetype,components',
  method: 'GET',
  headers: {
    Accept: 'application/json, text/plain, */*',
    Authorization: 'Basic c2FuZGVlcHJhai50YW5kb25AZ292LmJjLmNhOkNHSW9jdF8yMDIw',
    'User-Agent': 'axios/0.20.0'
  },
  agent: undefined,
  agents: { http: undefined, https: undefined },
  auth: undefined,
  hostname: 'bwa.nrs.gov.bc.ca',
  port: null,
  nativeProtocols: {
    'http:': {
      _connectionListener: [Function: connectionListener],
      METHODS: [Array],
      STATUS_CODES: [Object],
      Agent: [Function],
      ClientRequest: [Function: ClientRequest],
      IncomingMessage: [Function: IncomingMessage],
      OutgoingMessage: [Function: OutgoingMessage],
      Server: [Function: Server],
      ServerResponse: [Function: ServerResponse],
      createServer: [Function: createServer],
      get: [Function: get],
      request: [Function: request],
      maxHeaderSize: [Getter],
      globalAgent: [Getter/Setter]
    },
    'https:': {
      Agent: [Function: Agent],
      globalAgent: [Agent],
      Server: [Function: Server],
      createServer: [Function: createServer],
      get: [Function: get],
      request: [Function: request]
    }
  }
} +0ms
Fetching Jira Issue ONETEAM-429... done
Error: Unable to parse component description for nrdk
    at AxiosJiraClient.getComponentRepositoryInfo (/home/satandon/TeamZero/git/fork/nrdk/src/api/service/axios-jira-client.ts:66:13)
    at GitCheckout.getRepository (/home/satandon/TeamZero/git/fork/nrdk/src/commands/backlog/checkout.ts:120:51)
    at GitCheckout.run (/home/satandon/TeamZero/git/fork/nrdk/src/commands/backlog/checkout.ts:131:56)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at GitCheckout._run (/home/satandon/TeamZero/git/fork/nrdk/node_modules/@oclif/command/lib/command.js:43:20)
    at Config.runCommand (/home/satandon/TeamZero/git/fork/nrdk/node_modules/@oclif/config/lib/config.js:173:24)
    at Main.run (/home/satandon/TeamZero/git/fork/nrdk/node_modules/@oclif/command/lib/main.js:27:9)
    at Main._run (/home/satandon/TeamZero/git/fork/nrdk/node_modules/@oclif/command/lib/command.js:43:20)`

**Comment by cvarjao** [comment]
Currently, there is no support to GitHub, only bitbucket.

**Comment by 2011sandeepraj** [comment]
I didnt try command for a github repo. I am in plain Teamzero folder that isnt a repo itself and was hoping that the command will checkout Or Create a branch from Bitbucket by using the Jira ticket number. 
Steps to reproduce:
~/TeamZero$ npx @bcgov/nrdk backlog:checkout ONETEAM-429
