### ISSUE TITLE
Error running multiple tests in the same file

### ISSUE THREAD

**Issue by cvarjao** [BCDevOps/nrdk#9]
When running `test/commands/backlog/checkin.test.ts`, it only works if only 1 test active. I had to skip. the other ones just so that it could run successfully.

How to replicate:

1.  Edit `test/commands/backlog/checkin.test.ts`, and remove all the `.skip()` lines
2. Run that test file
    ```
    npm run mocha -- test/commands/backlog/checkin.test.ts
    ```

you should see the following error:
```
  1) backlog:checkin
       branch=false,pr=false:
     Error: Unable to parse Jira issue key from 'origin/feature/IRS-216'
      at Function.parseJiraIssueKeyFromUri (src/api/service/axios-jira-client.ts:22:19)
      at BacklogCheckin.run (src/commands/backlog/checkin.ts:20:44)
      at BacklogCheckin._run (node_modules/@oclif/command/lib/command.js:43:20)
      at Config.runCommand (node_modules/@oclif/config/lib/config.js:173:24)
      at Object.run (node_modules/@oclif/test/lib/command.js:20:13)
      at Context.run (node_modules/fancy-test/lib/base.js:68:25)
```

**Comment by mbystedt** [comment]
This is because adding a g to the JIRA_ISSUE_KEY_REGEX regex makes it stateful. Calling it twice then causes it return null. So, the unit test error is "correct". The 'g' can just be removed to solve this as the intention is to find the first (and probably only) match). See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec
